install updater

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,54 +1,10 @@
 #!/usr/bin/env bash
 
-ensure_link() {
-    local SUDO_CMD="${1}"
-    local SRC="${2%/}"
-    local DEST="${3%/}"
-    local NAME="${4}"
-
-    echo "Checking path executable ${NAME}"
-    local NEED_LINK=0
-    local LINK="$(readlink "${DEST}")"
-    if [ ! -z "${LINK}" ] && [ ! "${LINK}" = "${SRC}" ]; then
-        NEED_LINK=1
-        echo "Existing link points elsewhere, removing"
-        ${SUDO_CMD} rm "${DEST}"
-        if [ ! "${?}" -eq 0 ]; then
-            echo "Unable to remove bad link"
-            return 1
-        fi
-    fi
-    if [ ! -f "${DEST}" ]; then
-        NEED_LINK=1
-    fi
-    if [ "${NEED_LINK}" -eq 1 ]; then
-
-        echo "Creating system link"
-        if [ "${WINDOWS}" -eq 1 ]; then
-            local WIN_SRC="$(cygpath -w "${SRC}")"
-            local WIN_DEST="$(cygpath -w "${DEST}")"
-            local CMD_C="mklink ${WIN_DEST} ${WIN_SRC}"
-            cmd /C "\"${CMD_C}\"" > /dev/null 2>&1
-        else
-            ${SUDO_CMD} ln -s "${SRC}" "${DEST}"
-        fi
-
-        if [ ! "${?}" -eq 0 ]; then
-            echo "Unable to create system link"
-            return 1
-        fi
-    fi
-
-    if [ -L "${DEST}" ] && [ "$(readlink "${DEST}")" = "${SRC}" ]; then
-        echo "Link confirmed"
-    else
-        echo "Unable to install link"
-        return 1
-    fi
-}
-
 install_dotfile() {
     local SUDO_CMD="sudo"
+
+    echo "Installing dotfile"
+    echo
 
     local WINDOWS=0
     if [[ "${OS}" =~ .*indows.* ]]; then
@@ -121,20 +77,62 @@ install_dotfile() {
 
     # run to make sure config file is created for current user
     dotfile > /dev/null
-    local RESULT="${?}"
-    return "${RESULT}"
+    if [ "${?}" -eq 0 ]; then
+        echo "Install completed"
+        echo
+        exit 0
+    else
+        echo "Install failed"
+        echo
+        exit 1
+    fi
 }
 
-echo "Installing dotfile"
-echo
+ensure_link() {
+    local SUDO_CMD="${1}"
+    local SRC="${2%/}"
+    local DEST="${3%/}"
+    local NAME="${4}"
+
+    echo "Checking path executable ${NAME}"
+    local NEED_LINK=0
+    local LINK="$(readlink "${DEST}")"
+    if [ ! -z "${LINK}" ] && [ ! "${LINK}" = "${SRC}" ]; then
+        NEED_LINK=1
+        echo "Existing link points elsewhere, removing"
+        ${SUDO_CMD} rm "${DEST}"
+        if [ ! "${?}" -eq 0 ]; then
+            echo "Unable to remove bad link"
+            return 1
+        fi
+    fi
+    if [ ! -f "${DEST}" ]; then
+        NEED_LINK=1
+    fi
+    if [ "${NEED_LINK}" -eq 1 ]; then
+
+        echo "Creating system link"
+        if [ "${WINDOWS}" -eq 1 ]; then
+            local WIN_SRC="$(cygpath -w "${SRC}")"
+            local WIN_DEST="$(cygpath -w "${DEST}")"
+            local CMD_C="mklink ${WIN_DEST} ${WIN_SRC}"
+            cmd /C "\"${CMD_C}\"" > /dev/null 2>&1
+        else
+            ${SUDO_CMD} ln -s "${SRC}" "${DEST}"
+        fi
+
+        if [ ! "${?}" -eq 0 ]; then
+            echo "Unable to create system link"
+            return 1
+        fi
+    fi
+
+    if [ -L "${DEST}" ] && [ "$(readlink "${DEST}")" = "${SRC}" ]; then
+        echo "Link confirmed"
+    else
+        echo "Unable to install link"
+        return 1
+    fi
+}
 
 install_dotfile
-if [ "${?}" -eq 0 ]; then
-    echo "Install completed"
-    echo
-    exit 0
-else
-    echo "Install failed"
-    echo
-    exit 1
-fi
