chore: rename placeholder functions

diff --git a/src/dotfile b/src/dotfile
--- a/src/dotfile
+++ b/src/dotfile
@@ -32,7 +32,7 @@ find_me
 # Try to only use in subshells
 cdd() {
     cd "${1}" || {
-        TODO_error "Unable to cd to ${1}"
+        error "Unable to cd to ${1}"
         exit 1
     }
 }
@@ -117,7 +117,7 @@ dotfile_option_group() {
         fi
     done
     if [ "${FOUND}" -eq 0 ]; then
-        TODO_error "Invalid group: ${ACTIVE_GROUP}"
+        error "Invalid group: ${ACTIVE_GROUP}"
         return 1
     fi
     shift
@@ -146,7 +146,7 @@ dotfile_command_export() {
     fi
 
     if [ "${PREVIEW}" -eq 1 ]; then
-        TODO_info "Preview"
+        info "Preview"
         echo
     fi
 
@@ -171,7 +171,7 @@ dotfile_command_import() {
     title_import
 
     if [ "${PREVIEW}" -eq 1 ]; then
-        TODO_info "Preview"
+        info "Preview"
         echo
     fi
 
@@ -257,7 +257,7 @@ load_global_variables() {
     custom_groups=
     ensure_config || return 1
     if [ ! -d "${config_dir}" ]; then
-        TODO_error "failed to load a valid config dir"
+        error "failed to load a valid config dir"
         return 1
     fi
 
@@ -352,14 +352,14 @@ title_sync() {
 EOF
 }
 
-TODO_debug() {
+debug() {
     if [ "${OPT_VERBOSE}" -eq 0 ]; then
         return
     fi
     echo "DEBUG: ${1}"
 }
 
-TODO_info() {
+info() {
     # TODO
     # term_bold
     # term_fg_blue
@@ -372,7 +372,7 @@ TODO_info() {
     echo -e "${term_bold}${term_fg_blue}==> ${term_fg_white}${msg}${term_reset}" >&2
 }
 
-TODO_error() {
+error() {
     # TODO
     # term_bold
     # term_fg_red
@@ -385,14 +385,14 @@ TODO_error() {
     echo -e "${term_bold}${term_fg_red}ERROR: ${term_fg_white}${msg}${term_reset}" >&2
 }
 
-TODO_extname() {
+extname() {
     # filename has no extension
     [[ "${1}" == *.* ]] || return 0
 
     echo ".${1##*.}"
 }
 
-TODO_filename() {
+filename() {
     basename "$1" "$(extname "$1")"
 }
 
@@ -409,13 +409,13 @@ dotfile_git_add() {
     local TO_ADD="${1}"
     local IGNORE_RULES
     if ! dotfile_git add "${TO_ADD}"; then
-        TODO_error "Failed to stage ${TO_ADD} in git"
+        error "Failed to stage ${TO_ADD} in git"
 
         # Check if failed because of ignore rules
         IGNORE_RULES="$(dotfile_git check-ignore -v "${TO_ADD}")"
         if [ -n "${IGNORE_RULES}" ]; then
             echo
-            TODO_info "File ignored by git"
+            info "File ignored by git"
             echo "${IGNORE_RULES}"
         fi
 
@@ -430,11 +430,11 @@ clone_repo() {
     local NAME="${2}"
 
     if ! git clone "${GIT_REPO}" "${NAME}"; then
-        TODO_error "Failed to clone ${GIT_REPO}"
+        error "Failed to clone ${GIT_REPO}"
         return 1
     fi
 
-    TODO_info "Cloned ${GIT_REPO} => ${NAME}"
+    info "Cloned ${GIT_REPO} => ${NAME}"
     return 0
 }
 
@@ -444,17 +444,17 @@ display_ensure_dir() {
     local MESSAGE="${NAME} ${DIR}"
 
     if [ -z "${DIR}" ]; then
-        TODO_error "Dir param not set"
+        error "Dir param not set"
         return 1
     fi
 
     if [ -z "${NAME}" ]; then
-        TODO_error "Name param not set"
+        error "Name param not set"
         return 1
     fi
 
     if [ -d "${DIR}" ]; then
-        TODO_info "Found ${MESSAGE}"
+        info "Found ${MESSAGE}"
         return 0
     fi
 
@@ -462,7 +462,7 @@ display_ensure_dir() {
     local SUCCESS="${?}"
 
     if [ "${SUCCESS}" -eq 0 ]; then
-        TODO_info "Created ${MESSAGE}"
+        info "Created ${MESSAGE}"
     fi
 
     return "${SUCCESS}"
@@ -472,7 +472,7 @@ ensure_dir() {
     local DIR="${1}"
 
     if [ -z "${DIR}" ]; then
-        TODO_error "Dir param not set"
+        error "Dir param not set"
         return 1
     fi
 
@@ -481,7 +481,7 @@ ensure_dir() {
     fi
 
     if ! mkdir -p "${DIR}"; then
-        TODO_error "Failed to create ${DIR}"
+        error "Failed to create ${DIR}"
         return 1
     fi
 
@@ -494,7 +494,7 @@ ensure_file() {
     [ -f "${FILE}" ] && return 0
 
     if ! touch "${FILE}"; then
-        TODO_error "Failed to create ${FILE}"
+        error "Failed to create ${FILE}"
         return 1
     fi
 
@@ -570,7 +570,10 @@ smart_link() {
                 # File contents differ
                 if [ -f "${SRC_FILE}" ] && [ -f "${DEST_FILE}" ] \
                         && ! cmp --silent "${SRC_FILE}" "${DEST_FILE}" && [ "${OPT_VERBOSE}" -eq 1 ]; then
-                    git --no-pager diff --no-index "${SRC_FILE}" "${DEST_FILE}"
+                    git --no-pager diff --no-index "${SRC_FILE}" "${DEST_FILE}" || {
+                        error "failed to display diff in pager"
+                        return 1
+                    }
                 fi
             else
                 backup_move "${DEST_DIR}" "${FILE_NAME}" "${DISPLAY_FILE_REF}" || return 1
@@ -621,7 +624,7 @@ create_link() {
         local CMD_C="mklink ${OPT}${WIN_DEST_FILE} ${WIN_SRC_FILE}"
 
         # Windows link attempt
-        TODO_debug "cmd //C \"${CMD_C}\""
+        debug "cmd //C \"${CMD_C}\""
 
         # Double forward slash to prevent msys messing with params
         cmd //C "${CMD_C}" > /dev/null || return 1
@@ -644,11 +647,11 @@ backup_move() {
     local DEST="${SRC/${HOME_DIR}/${BACKUP_DIR}}"
     local BACKUP_FILE
 
-    BACKUP_FILE="$(TODO_filename "${FILE}")_${TIMESTAMP}$(TODO_extname "${FILE}")"
+    BACKUP_FILE="$(filename "${FILE}")_${TIMESTAMP}$(extname "${FILE}")"
 
     if [ ! -d "${DEST}" ]; then
         if ! mkdir -p "${DEST}"; then
-            TODO_error "Unable to create backup dir ${DEST}"
+            error "Unable to create backup dir ${DEST}"
             return 1
         fi
     fi
@@ -688,7 +691,7 @@ ensure_nested_dir() {
     local IGNORE_FILE
 
     if [ ! -d "${DIR}" ] && ! mkdir -p "${DIR}"; then
-        TODO_error "Unable to create nested dir: ${DIR}"
+        error "Unable to create nested dir: ${DIR}"
         return 1
     fi
 
@@ -700,7 +703,7 @@ ensure_nested_dir() {
         IGNORE_FILE="${CURRENT_DIR}/${DOTFILE_MARKER}"
         if [ ! -f "${IGNORE_FILE}" ]; then
             if ! touch "${IGNORE_FILE}"; then
-                TODO_error "Unable to create ${IGNORE_FILE}"
+                error "Unable to create ${IGNORE_FILE}"
                 return 1
             fi
             dotfile_git_add "${IGNORE_FILE}" || return 1
@@ -718,22 +721,22 @@ cleanup_nested_dir() {
     local NESTED_DIR
 
     if [ -z "${DOTFILE_GROUP_DIR}" ]; then
-        TODO_error "Missing dotfile group dir param"
+        error "Missing dotfile group dir param"
         return 1
     fi
 
     if [ ! -d "${DOTFILE_GROUP_DIR}" ]; then
-        TODO_error "Dotfile group dir must be a directory: ${DOTFILE_GROUP_DIR}"
+        error "Dotfile group dir must be a directory: ${DOTFILE_GROUP_DIR}"
         return 1
     fi
 
     if [ -z "${EXPORT_DIR}" ]; then
-        TODO_error "Missing export dir param"
+        error "Missing export dir param"
         return 1
     fi
 
     if [ ! -d "${EXPORT_DIR}" ]; then
-        TODO_error "Export dir must be a directory: ${EXPORT_DIR}"
+        error "Export dir must be a directory: ${EXPORT_DIR}"
         return 1
     fi
 
@@ -754,13 +757,13 @@ cleanup_nested_dir() {
         done < <(find "${NESTED_DIR}" -maxdepth 1 -mindepth 1 -print0)
 
         if ! rm "${IGNORE_FILE}"; then
-            TODO_error "Failed to remove ${IGNORE_FILE}"
+            error "Failed to remove ${IGNORE_FILE}"
             return 1
         fi
 
         # Leave dir, delete it, reset NESTED_DIR
         if ! rmdir "${NESTED_DIR}"; then
-            TODO_error "Failed to remove ${NESTED_DIR}"
+            error "Failed to remove ${NESTED_DIR}"
             return 1
         fi
         dotfile_git_add "${NESTED_DIR}" || return 1
@@ -777,7 +780,7 @@ ensure_config() {
 
     if [ ! -d "${PATH}" ]; then
         if ! mkdir -p "${PATH_CONFIG}"; then
-            TODO_error "Unable to create config dir: ${PATH_CONFIG}"
+            error "Unable to create config dir: ${PATH_CONFIG}"
             exit 1
         fi
     fi
@@ -785,19 +788,19 @@ ensure_config() {
     if [ ! -f "${FILE}" ]; then
         create_config "${FILE}"
         if [ ! -f "${FILE}" ]; then
-            TODO_error "Unable to create config file: ${FILE}"
+            error "Unable to create config file: ${FILE}"
             exit 1
         fi
     fi
 
     cfg_parser "${FILE}"
     if ! cfg_section_dotfile; then
-        TODO_error "Failed to load config: ${FILE}"
+        error "Failed to load config: ${FILE}"
         exit 1
     fi
 
     if [ "${config_version}" != "${MAJOR_VERSION}" ]; then
-        TODO_error "Invalid config version!"
+        error "Invalid config version!"
         echo "Config created for a different program version and may be incompatible"
         echo "  Program version: ${MAJOR_VERSION}"
         echo "   Config version: ${config_version}"
@@ -891,7 +894,7 @@ export_dotfile() {
     fi
 
     if [ "$(commonpath "${HOME_DIR}" "${EXPORT_FILE}")" != "${HOME_DIR}" ]; then
-        TODO_error "File must be inside home dir: ${HOME_DIR}: ${EXPORT_FILE}"
+        error "File must be inside home dir: ${HOME_DIR}: ${EXPORT_FILE}"
         echo
         return 1
     fi
@@ -903,11 +906,11 @@ export_dotfile() {
 
     REPO_FILE="$(readlink "${EXPORT_FILE}")"
     if [ -z "${REPO_FILE}" ]; then
-        TODO_error "Missing linked file for ${EXPORT_FILE}"
+        error "Missing linked file for ${EXPORT_FILE}"
         return 1
     fi
     if [ "$(commonpath "${DOTFILES_DIR}" "${REPO_FILE}")" != "${DOTFILES_DIR}" ]; then
-        TODO_error "Link must point to file inside ${DOTFILES_DIR}: ${REPO_FILE}"
+        error "Link must point to file inside ${DOTFILES_DIR}: ${REPO_FILE}"
         echo
         return 1
     fi
@@ -921,11 +924,11 @@ export_dotfile() {
     fi
 
     if ! rm "${EXPORT_FILE}"; then
-        TODO_error "Failed to remove link ${EXPORT_FILE}"
+        error "Failed to remove link ${EXPORT_FILE}"
         return 1
     fi
     if ! mv "${REPO_FILE}" "${EXPORT_FILE}"; then
-        TODO_error "Failed to restore ${EXPORT_FILE}"
+        error "Failed to restore ${EXPORT_FILE}"
         return 1
     fi
     dotfile_git_add "${REPO_FILE}" || return 1
@@ -983,7 +986,7 @@ import_dotfile() {
 
 display_ensure_filesystem() {
     if [ "${PREVIEW}" -eq 1 ]; then
-        TODO_info "Preview"
+        info "Preview"
         echo
     fi
 
@@ -1009,12 +1012,12 @@ ensure_dotfiles_dir() {
     [ -d "${DOTFILES_DIR}" ] && return 0
 
     if [ -z "${DOTFILES_REPO}" ]; then
-        TODO_error "Missing dotfiles repo config"
+        error "Missing dotfiles repo config"
         return 1
     fi
 
     if ! clone_repo "${DOTFILES_REPO}" "${DOTFILES_DIR}"; then
-        TODO_error "Failed to clone ${DOTFILES_REPO}"
+        error "Failed to clone ${DOTFILES_REPO}"
         echo
         return 1
     fi
@@ -1047,18 +1050,18 @@ sync_config_to_home() {
     # Skip files handled by a previous group
     for GROUP in "${DOTFILE_GROUP_LIST[@]}"; do
         SRC_DIR="${DOTFILES_DIR}/${GROUP}"
-        TODO_debug "Checking ${SRC_DIR}"
+        debug "Checking ${SRC_DIR}"
 
         while read -r -d $'\0' FILE; do
             # Skip dir if it contains a `${DOTFILE_MARKER}`
             if [ -d "${FILE}" ] && [ -f "${FILE}/${DOTFILE_MARKER}" ]; then
-                TODO_debug "Skip nested dir: ${FILE}"
+                debug "Skip nested dir: ${FILE}"
                 continue
             fi
 
             # Skip file unless it's next to a `${DOTFILE_MARKER}`
             if [ -e "${FILE}" ] && [ ! -f "${FILE%/*}/${DOTFILE_MARKER}" ]; then
-                TODO_debug "Skip non dotfile: ${FILE}"
+                debug "Skip non dotfile: ${FILE}"
                 continue
             fi
 
@@ -1072,7 +1075,7 @@ sync_config_to_home() {
     done
 
     if [ "${#EXCLUDE_PATHS[@]}" -eq 0 ]; then
-        TODO_info "No files in config repo, get started with \"dotfile import\""
+        info "No files in config repo, get started with \"dotfile import\""
     fi
     echo
 
